if(__AUTUTILS_CHECK_TYPE)
  return()
endif()
set(__AUTUTILS_CHECK_TYPE 1)

include(AututilsCheckTypeSize)

include(AututilsWriteToConfigHeader)

macro(aututils_check_type type)
  string(MAKE_C_IDENTIFIER "${type}" _var)
  string(TOUPPER "${_var}" _var)
  if(NOT DEFINED _test_${_var})
    if(ARGN)
      set(CMAKE_REQUIRED_INCLUDES ${ARGN})
    endif()
    aututils_check_type_size(${type} _test_${_var})
    if(_test_${_var})
      set(HAVE_${_var} ON)
      aututils_write_to_config_header("#define HAVE_${_var}")
    else()
      aututils_write_to_config_header("/* #undef HAVE_${_var} */")
    endif()
  endif()
endmacro()
