if(__autoutils_check_lib)
  return()
endif()
set(__autoutils_check_lib 1)

include(CheckLibraryExists)

include(AutoutilsWriteToConfigHeader)

macro(autoutils_check_lib lib func)
  string(MAKE_C_IDENTIFIER "${lib}" _var)
  string(TOUPPER "${_var}" _var)
  if(NOT DEFINED _exists_${lib})
    check_library_exists(${lib} ${func} "" _exists_${lib})
    if(_exists_${lib})
      autoutils_write_to_config_header("#define HAVE_LIB${_var}")
    else()
      autoutils_write_to_config_header("/* #undef HAVE_LIB${_var} */")
    endif()
  endif()

  if(_exists_${lib})
    set(HAVE_LIB${_var} ON)
  endif()
endmacro()
