if(__CHECK_LIB)
  return()
endif()
set(__CHECK_LIB 1)

include(CheckLibraryExists)

include(WriteToConfigHeader)

macro(check_lib lib func)
  if(NOT DEFINED _exists_${lib})
    check_library_exists(${lib} ${func} "" _exists_${lib})
    string(MAKE_C_IDENTIFIER "${lib}" _var)
    string(TOUPPER "${_var}" _var)
    if(_exists_${lib})
      set(HAVE_LIB${_var} ON)
      write_to_config_header("#define HAVE_LIB${_var}")
    else()
      write_to_config_header("/* #undef HAVE_LIB${_var} */")
    endif()
  endif()
endmacro()
