if(__INCLUDES_DEFAULT)
  return()
endif()
set(__INCLUDES_DEFAULT 1)

include(CheckHeader)

check_header("inttypes.h")
check_header("memory.h")
check_header("stddef.h")
check_header("stdint.h")
check_header("stdlib.h")
check_header("string.h")
check_header("strings.h")
check_header("sys/stat.h")
check_header("sys/types.h")
check_header("unistd.h")

set(includes_default "stdio.h")
if(HAVE_SYS_TYPES_H)
  list(APPEND includes_default "sys/types.h")
endif()
if(HAVE_SYS_STAT_H)
  list(APPEND includes_default "sys/stat.h")
endif()
if(HAVE_STDLIB_H)
  list(APPEND includes_default "stdlib.h")
endif()
if(HAVE_STDDEF_H)
  set(STDC_HEADERS ON)
  list(APPEND includes_default "stddef.h")
endif()
if(HAVE_STRING_H)
  if(NOT STDC_HEADERS AND HAVE_MEMORY_H)
    list(APPEND includes_default "memory.h")
  endif()
  list(APPEND includes_default "string.h")
endif()
if(HAVE_STRINGS_H)
  list(APPEND includes_default "strings.h")
endif()
if(HAVE_INTTYPES_H)
  list(APPEND includes_default "inttypes.h")
endif()
if(HAVE_STDINT_H)
  list(APPEND includes_default "stdint.h")
endif()
if(HAVE_UNISTD_H)
  list(APPEND includes_default "unistd.h")
endif()
